[2024-06-08T16:14:26.258+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T16:14:26.272+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pg_loader.load_categories manual__2024-06-08T16:14:25.778371+00:00 [queued]>
[2024-06-08T16:14:26.276+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pg_loader.load_categories manual__2024-06-08T16:14:25.778371+00:00 [queued]>
[2024-06-08T16:14:26.277+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T16:14:26.285+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_categories> on 2024-06-08 16:14:25.778371+00:00
[2024-06-08T16:14:26.289+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1252) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T16:14:26.290+0000] {standard_task_runner.py:63} INFO - Started process 1256 to run task
[2024-06-08T16:14:26.290+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pg_loader', 'load_categories', 'manual__2024-06-08T16:14:25.778371+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/load_pg_dag.py', '--cfg-path', '/tmp/tmpninrapko']
[2024-06-08T16:14:26.291+0000] {standard_task_runner.py:91} INFO - Job 49: Subtask load_categories
[2024-06-08T16:14:26.319+0000] {task_command.py:426} INFO - Running <TaskInstance: pg_loader.load_categories manual__2024-06-08T16:14:25.778371+00:00 [running]> on host 945bac6cf142
[2024-06-08T16:14:26.369+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pg_loader' AIRFLOW_CTX_TASK_ID='load_categories' AIRFLOW_CTX_EXECUTION_DATE='2024-06-08T16:14:25.778371+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-08T16:14:25.778371+00:00'
[2024-06-08T16:14:26.370+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T16:14:26.382+0000] {base.py:84} INFO - Using connection ID '***-etl' for task execution.
[2024-06-08T16:14:26.388+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T16:14:26.390+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T16:14:26.396+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pg_loader, task_id=load_categories, run_id=manual__2024-06-08T16:14:25.778371+00:00, execution_date=20240608T161425, start_date=20240608T161426, end_date=20240608T161426
[2024-06-08T16:14:26.429+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T16:14:26.439+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T16:14:26.440+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
